services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: auto-span-example
    ports:
      - "3306:3306"
    volumes:
      - ./sample.sql:/docker-entrypoint-initdb.d/sample.sql:ro

  jaeger:
    platform: linux/x86_64
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "4317:4317"
      - "16686:16686"
